### ISSUE TITLE
Create Reading Event Button with Current Page

### ISSUE THREAD

**Issue by a2brew** [wars2k/booktracker#18]
Similar to Jelu, I think it would be handy to be able to add 'reading events', specifically what page you're currently on for a given book. From there, the app can track 'percentage read' against the page count listed in the metadata.

![Add Event Button](https://github.com/wars2k/booktracker/assets/88284052/b21e91e2-ed19-4310-b6ea-bb0bc7c2bce7)

**Comment by wars2k** [comment]
Implemented in [v0.6-beta](https://github.com/wars2k/booktracker/releases/tag/v0.6-beta).
